# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pw_hash',
            new_name='password',
        ),
    ]
